### ISSUE TITLE
question about using this plugin

### ISSUE THREAD

**Issue by carlosmaid** [sirhamsteralot/HaE-PluginCore#1]
Hi, can i port my mods scripts to a this plugin system, if the scripts on server side are using [MySessionComponentDescriptor(MyUpdateOrder.AfterSimulation)] of mysessioncomponentbase and MyGameLogicComponent ?

I tried it but if it compiles without errors, my code is not initialized since it does it from
         public override void UpdateAfterSimulation () and not plugin update() method.. 

thanks!

**Comment by sirhamsteralot** [comment]
Id generally not recommend porting mods to this plugin system if it requires serverside code (or if you dont require any of the additional power a plugin gives) (this plugin only runs on the client). But you can prolly look at MyGameLogic.RegisterForUpdate or something.
